### ISSUE TITLE
MergeSort mid issue

### ISSUE THREAD

**Issue by dinoiam** [king-prawns/Algorithm#1]
Hi king-prawns, should this line be something like this  ` const mid = Math.floor(N/2);` ? Otherwise if the length of the array is odd you will get also the decimal part of the number. 
https://github.com/king-prawns/Algorithm/blob/c799da3fe4f6d5df4bcb6dbcdd72ade96b088996/MergeSort/index.ts#L6

**Comment by king-prawns** [comment]
Hi mate,
sure, you are right, I am going to update it.
Feel free to open a PR next time!

**Comment by king-prawns** [comment]
done 895581b183c48199af721fe6e556925b92827235
